version: '3'
services:
  web-server:
    build: .
    command: flask run --host=0.0.0.0
    environment:
      - FLASK_APP=main.py
    ports:
      - "5000:5000"
    volumes:
      - ./resources/user_images:/app/resources/user_images
